//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firsaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public string URL { get; set; }
        public string Price1 { get; set; }
        public Nullable<int> PostId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
